version: "3.0"

services: 
    redis:
        container_name: redis
        image: redis
        ports: 
            - "6379:6379"
        restart: on-failure
        networks: 
            - my-server

    server:
        container_name: server
        build: 
            context: server
            dockerfile: Dockerfile
        ports: 
            - "8000:8000"
        restart: on-failure
        networks: 
            - my-server
        depends_on: 
            - redis

    nginx:
        container_name: nginx
        volumes: 
            - /usr/local/nginx/logs:/var/log/nginx
            - /usr/local/nginx/html:/usr/share/nginx/html
            - /usr/local/nginx/conf.d/:/etc/nginx/conf.d
            - /usr/local/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - /usr/local/nginx/ssl:/etc/nginx/ssl
        build: 
            context: nginx
            dockerfile: Dockerfile
        ports: 
            - "80:80"
            - "443:443"
        restart: on-failure
        networks: 
            - my-server
        depends_on: 
            - redis
            - server
        privileged: true

networks:
    my-server:
